### ISSUE TITLE
Improve local setup instructions

### ISSUE THREAD

**Issue by alabhyajindal** [andreterron/mainframe#36]
The instructions for setting up Mainframe locally could be improved. The README should ideally start from the `git clone` step.

I took the following steps:
1. Clone the repo
2. `npm i` to install dependencies
3. Ran `npm run dev` and got the message 'Your Mainframe is up!`

But when I visit http://localhost:8745/ - I see `Cannot GET /`

**Comment by andreterron** [comment]
Fixed @alabhyajindal!

The API and the app used to share the same url, but they were separated into `localhost:8744` (app) and `localhost:8745` (api). I updated the message to show the right port and added a redirect from the root of the API to the app URL.
