### ISSUE TITLE
Landing page github link points to Discord

### ISSUE THREAD

**Issue by MartinBernstorff** [andreterron/mainframe#55]
Super interested in mainframe! Could make a lot of my personal projects much easier (and more fun!).

<img width="315" alt="image" src="https://github.com/andreterron/mainframe/assets/8526086/37a1cce8-4bad-494f-adc6-d6ee7c5fef34">

This link points to the Discord :-)

**Comment by andreterron** [comment]
Fixed on July 3rd! Apologies for missing your issue here
